spring:
  application:
    name: belajar-crud

  datasource:
    url: jdbc:postgresql://localhost:5444/belajar_crud
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8585